### ISSUE TITLE
has-flag.js - seems to assume cli use, causing issue during synchronous module loading

### ISSUE THREAD

**Issue by YeeP79** [DABH/colors.js#41]
The issue looks to be here:
https://github.com/DABH/colors.js/blob/master/lib/system/has-flag.js#L28

Node is just loading all imports into memory like it always does, and an error shows up:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/8461870/231600568-8849c169-a143-4e19-a7c8-5b3800da73d9.png">

Some debugging ahead of time will show that neither argv nor process.argv are defined. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/8461870/231600707-0d1db5b8-3380-4b26-a085-2613bcc3e45e.png">

Looking for any suggestions as to what can cause this. As the dependency chain comes from winston, I would image you would be seeing more issues raised if it was a straight up bug. Thank you

**Comment by valueof** [comment]
I was just dealing with a similar issue. In our case, we have a pretty generic Next app. We've decided to add `winston` for structured logging and this error pops up only when logging is being added to Next Middleware (`middleware.ts`). I believe this happens because middleware uses [Edge Runtime](https://beta.nextjs.org/docs/rendering/edge-and-nodejs-runtimes#nodejs-runtime) which doesn't have `process.argv`.

For now, I've moved logging code out of middleware. If I initialize the logger anywhere in server-side `pages/api` it seems to work fine.

**Comment by axelvaindal** [comment]
I just had the same issue with Next 13 using app directory.

As stated by @valueof, running winston logger inside middleware breaks. I've also moved my logger out for now.

**Comment by copini** [comment]
Ran into the same issue using Next 13 (middleware + app directory). Was able to fix it locally using [yarn patch](https://yarnpkg.com/cli/patch), applying the same minor change as in PR #44.

**Comment by DABH** [comment]
This has been closed and released in v1.6.0.  Thanks all!
